
module std.outofmemory;

pragma(msg, "std.exception:Now all exceptions are situated in module std.exception");

public import std.exception;

